### ISSUE TITLE
thanks for the tool! Having some issues with creating from file

### ISSUE THREAD

**Issue by aaronbkano** [Rahien/aoe2-build-orders#1]
I love the tool, found it via reddit. Thanks for sharing! Just wanted to mention that I wasn't able to get the load from file feature to work. I downloaded the 21 Pop Scouts order using the download feature. Then, on a windows laptop in Chrome, I click "New Build" then "From File". I see a dialog for choosing my file; I choose the json 21 Pop Scouts file and the title is displayed in the window. I then hit "submit" and nothing happens. LMK if you would like any more details but I'll completely understand if you're not up for maintaining this thing.

**Comment by Rahien** [comment]
Thanks a lot for flagging this! I'll fix this as soon as possible!
Will keep you posted!

**Comment by Rahien** [comment]
Hi!

This was clearly a bit of a forgotten corner in the app, sorry about that!
This should now be fixed. As the app caches its assets on your device, you will need to close the app and start it again for the changes to come in though...

Thanks again for pointing this out!

**Comment by aaronbkano** [comment]
I tried this on my phone and found reloading the page after tapping submit
did work! This will be super helpful because this way I can write build
orders either in-app or as json on my laptop then load them on my phone.
