### ISSUE TITLE
a couple more potential bugs I found

### ISSUE THREAD

**Issue by aaronbkano** [Rahien/aoe2-build-orders#2]
Hi Rahien, thanks for the quick fix! I've found some other behaviors that I'm surprised by and seem likely to be unintended. See attached build order JSON. Again, no pressure if you don't have time/inclination to bugfix.

The first three steps don't affect the number of vils shown gathering food or wood; I would have expected the tree icon to mean straggler trees and therefore to be counted towards wood. I would've expected the food icon to be counted as food too.

The next two steps work as expected.

The step where you go to feudal age and transfer one vil from sheep to farms causes the number of vils working on food to increase by one, while the total vil count remains constant. This also happens if you transfer from boar to sheep during feudal, though it's not shown in this build order. Also I noticed you can transfer vils you don't have, resulting in a negative number of wood cutters.

And finally, the last step is never executed or reflected. I would've expected that if you run the whole build order, it'd run transfers sitting at the end and reflect those in the resource totals.

[unexpected behavior examples.txt](https://github.com/Rahien/aoe2-build-orders/files/5455223/unexpected.behavior.examples.txt)

**Comment by Rahien** [comment]
Thanks again for the report! Will look into it as soon as possible 👍

**Comment by Rahien** [comment]
Hi!

The example you included was super useful in pinpointing these issues! They should all be fixed now. 

I noticed that the feudal age step had a target set, probably a result of it being changed to feudal from a create step. However, if this was your intention note that the target will now no longer be taken into account for steps other than 'create', 'move' or 'build'.

As before, the heavy caching for PWAs may require you to close and restart the app a couple of times before the changes take effect... You can tell it refreshed if you don't see the target in the feudal age step anymore (a sheep I believe).

Don't hesitate to let me know of new features you'd like to see!
